### ISSUE TITLE
How to pause

### ISSUE THREAD

**Issue by Zxmon-code** [Prayag2/pomo#3]
from the available options I take, that there is some way to pause the timer, but I just can't figure out how.
Sorry if it is listed somewhere and I just dont get it.

**Comment by Prayag2** [comment]
If you use dunst, you can use its context menu to pause the timer. You need `dmenu` or a drop-in dmenu replacement like `rofi -dmenu` for it to work. You can set `dmenu=<path to dmenu>` in `~/.config/dunst/dunstrc` and after restarting dunst daemon, you can middle click on the notification to access the context menu.

**Comment by Prayag2** [comment]
Here's a video- 

https://user-images.githubusercontent.com/39525869/219933559-baee38be-72ff-4e51-b752-6a7ecad92919.mp4

This is from `~/.config/dunst/dunstrc`-
```rc
[global]
    dmenu = /usr/bin/rofi -dmenu -p  rofi -theme-str " window {location: north east; x-offset: -370px; y-offset: 50px; width: 500px;}" -hover-select -me-select-entry '' -me-accept-entry MousePrimary -i

    mouse_left_click = close_current
    mouse_middle_click = do_action, close_current
    mouse_right_click = close_all
```

**Comment by Zxmon-code** [comment]
Thanks a lot, I have not yet gotten it to work but that is because of dunst.
